name: Go Application Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    # Cache Go modules
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Run Makefile Test
    - name: Run Tests with Makefile
      run: |
        make test

    # Build Docker Image
    - name: Build Docker Image
      run: |
        make docker-build

    # Run Tests Inside Docker
    - name: Run Tests Inside Docker
      run: |
        make docker-test

    # Cleanup Docker Resources (optional)
    - name: Cleanup Docker
      run: |
        docker image prune -f
